name: release

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: version

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: out

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          PACKAGE_VERSION: ${{ github.event.inputs.version || github.ref_name }}
        with:
          files: out
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ env.PACKAGE_VERSION }}
          tag_name: v${{ env.PACKAGE_VERSION }}
          draft: true
          prerelease: false

      - name: Release latest
        if: github.event_name == 'push' && github.ref.startsWith('refs/tags/')
        uses: softprops/action-gh-release@v2
        env:
          PACKAGE_VERSION: ${{ github.ref_name }}
        with:
          files: out
          token: ${{ secrets.GITHUB_TOKEN }}
          name: latest
          draft: false
          prerelease: false
